/* eslint-disable */

import React from 'react';
import { components } from 'react-select';

export const DropdownIndicator = (props) => {
    const { selectProps } = props;
    return (
        <components.DropdownIndicator {...props}>
            <img src={selectProps.dropdownIndicatorImg ?? './assets/images/drop-down-arrow.svg'} alt="drop-down" />
        </components.DropdownIndicator>
    );
};

export const selectStyles = {
    option: (styles) => {
        return {
            ...styles,
            backgroundColor: '#1a1a1a',
            borderColor: '#1a1a1a',
        };
    },
};

export const languageOptions = [
    // length 142 [
    { label: 'Afrikaans', value: 'Afrikaans', slug: 'af', icon: '' },
    { label: 'Albanian - shqip', value: 'Albanian - shqip', slug: 'sq', icon: '' },
    { label: 'Amharic - አማርኛ', value: 'Amharic - አማርኛ', slug: 'am', icon: '' },
    { label: 'Arabic - العربية', value: 'Arabic - العربية', slug: 'ar', icon: '' },
    { label: 'Aragonese - aragonés', value: 'Aragonese - aragonés', slug: 'an', icon: '' },
    { label: 'Armenian - հայերեն', value: 'Armenian - հայերեն', slug: 'hy', icon: '' },
    { label: 'Asturian - asturianu', value: 'Asturian - asturianu', slug: 'ast', icon: '' },
    { label: 'Azerbaijani - azərbaycan dili', value: 'Azerbaijani - azərbaycan dili', slug: 'az', icon: '' },
    { label: 'Basque - euskara', value: 'Basque - euskara', slug: 'eu', icon: '' },
    { label: 'Belarusian - беларуская', value: 'Belarusian - беларуская', slug: 'be', icon: '' },
    { label: 'Bengali - বাংলা', value: 'Bengali - বাংলা', slug: 'bn', icon: '' },
    { label: 'Bosnian - bosanski', value: 'Bosnian - bosanski', slug: 'bs', icon: '' },
    { label: 'Breton - brezhoneg', value: 'Breton - brezhoneg', slug: 'br', icon: '' },
    { label: 'Bulgarian - български', value: 'Bulgarian - български', slug: 'bg', icon: '' },
    { label: 'Catalan - català', value: 'Catalan - català', slug: 'ca', icon: '' },
    {
        label: 'Central Kurdish - کوردی (دەستنوسی عەرەبی)',
        value: 'Central Kurdish - کوردی (دەستنوسی عەرەبی)',
        slug: 'ckb',
        icon: '',
    },
    { label: 'Chinese - 中文', value: 'Chinese - 中文', slug: 'zh', icon: '' },
    {
        label: 'Chinese (Hong Kong) - 中文（香港）',
        value: 'Chinese (Hong Kong) - 中文（香港）',
        slug: 'zh-HK',
        icon: '',
    },
    {
        label: 'Chinese (Simplified) - 中文（简体）',
        value: 'Chinese (Simplified) - 中文（简体）',
        slug: 'zh-CN',
        icon: '',
    },
    {
        label: 'Chinese (Traditional) - 中文（繁體）',
        value: 'Chinese (Traditional) - 中文（繁體）',
        slug: 'zh-TW',
        icon: '',
    },
    { label: 'Corsican', value: 'Corsican', slug: 'co', icon: '' },
    { label: 'Croatian - hrvatski', value: 'Croatian - hrvatski', slug: 'hr', icon: '' },
    { label: 'Czech - čeština', value: 'Czech - čeština', slug: 'cs', icon: '' },
    { label: 'Danish - dansk', value: 'Danish - dansk', slug: 'da', icon: '' },
    { label: 'Dutch - Nederlands', value: 'Dutch - Nederlands', slug: 'nl', icon: '' },
    { label: 'English', value: 'English', slug: 'en', icon: '' },
    { label: 'English (Australia)', value: 'English (Australia)', slug: 'en-AU', icon: '' },
    { label: 'English (Canada)', value: 'English (Canada)', slug: 'en-CA', icon: '' },
    { label: 'English (India)', value: 'English (India)', slug: 'en-IN', icon: '' },
    { label: 'English (New Zealand)', value: 'English (New Zealand)', slug: 'en-NZ', icon: '' },
    { label: 'English (South Africa)', value: 'English (South Africa)', slug: 'en-ZA', icon: '' },
    { label: 'English (United Kingdom)', value: 'English (United Kingdom)', slug: 'en-GB', icon: '' },
    { label: 'English (United States)', value: 'English (United States)', slug: 'en-US', icon: '' },
    { label: 'Esperanto - esperanto', value: 'Esperanto - esperanto', slug: 'eo', icon: '' },
    { label: 'Estonian - eesti', value: 'Estonian - eesti', slug: 'et', icon: '' },
    { label: 'Faroese - føroyskt', value: 'Faroese - føroyskt', slug: 'fo', icon: '' },
    { label: 'Filipino', value: 'Filipino', slug: 'fil', icon: '' },
    { label: 'Finnish - suomi', value: 'Finnish - suomi', slug: 'fi', icon: '' },
    { label: 'French - français', value: 'French - français', slug: 'fr', icon: '' },
    {
        label: 'French (Canada) - français (Canada)',
        value: 'French (Canada) - français (Canada)',
        slug: 'fr-CA',
        icon: '',
    },
    {
        label: 'French (France) - français (France)',
        value: 'French (France) - français (France)',
        slug: 'fr-FR',
        icon: '',
    },
    {
        label: 'French (Switzerland) - français (Suisse)',
        value: 'French (Switzerland) - français (Suisse)',
        slug: 'fr-CH',
        icon: '',
    },
    { label: 'Galician - galego', value: 'Galician - galego', slug: 'gl', icon: '' },
    { label: 'Georgian - ქართული', value: 'Georgian - ქართული', slug: 'ka', icon: '' },
    { label: 'German - Deutsch', value: 'German - Deutsch', slug: 'de', icon: '' },
    {
        label: 'German (Austria) - Deutsch (Österreich)',
        value: 'German (Austria) - Deutsch (Österreich)',
        slug: 'de-AT',
        icon: '',
    },
    {
        label: 'German (Germany) - Deutsch (Deutschland)',
        value: 'German (Germany) - Deutsch (Deutschland)',
        slug: 'de-DE',
        icon: '',
    },
    {
        label: 'German (Liechtenstein) - Deutsch (Liechtenstein)',
        value: 'German (Liechtenstein) - Deutsch (Liechtenstein)',
        slug: 'de-LI',
        icon: '',
    },
    {
        label: 'German (Switzerland) - Deutsch (Schweiz)',
        value: 'German (Switzerland) - Deutsch (Schweiz)',
        slug: 'de-CH',
        icon: '',
    },
    { label: 'Greek - Ελληνικά', value: 'Greek - Ελληνικά', slug: 'el', icon: '' },
    { label: 'Guarani', value: 'Guarani', slug: 'gn', icon: '' },
    { label: 'Gujarati - ગુજરાતી', value: 'Gujarati - ગુજરાતી', slug: 'gu', icon: '' },
    { label: 'Hausa', value: 'Hausa', slug: 'ha', icon: '' },
    { label: 'Hawaiian - ʻŌlelo Hawaiʻi', value: 'Hawaiian - ʻŌlelo Hawaiʻi', slug: 'haw', icon: '' },
    { label: 'Hebrew - עברית', value: 'Hebrew - עברית', slug: 'he', icon: '' },
    { label: 'Hindi - हिन्दी', value: 'Hindi - हिन्दी', slug: 'hi', icon: '' },
    { label: 'Hungarian - magyar', value: 'Hungarian - magyar', slug: 'hu', icon: '' },
    { label: 'Icelandic - íslenska', value: 'Icelandic - íslenska', slug: 'is', icon: '' },
    { label: 'Indonesian - Indonesia', value: 'Indonesian - Indonesia', slug: 'id', icon: '' },
    { label: 'Interlingua', value: 'Interlingua', slug: 'ia', icon: '' },
    { label: 'Irish - Gaeilge', value: 'Irish - Gaeilge', slug: 'ga', icon: '' },
    { label: 'Italian - italiano', value: 'Italian - italiano', slug: 'it', icon: '' },
    {
        label: 'Italian (Italy) - italiano (Italia)',
        value: 'Italian (Italy) - italiano (Italia)',
        slug: 'it-IT',
        icon: '',
    },
    {
        label: 'Italian (Switzerland) - italiano (Svizzera)',
        value: 'Italian (Switzerland) - italiano (Svizzera)',
        slug: 'it-CH',
        icon: '',
    },
    { label: 'Japanese - 日本語', value: 'Japanese - 日本語', slug: 'ja', icon: '' },
    { label: 'Kannada - ಕನ್ನಡ', value: 'Kannada - ಕನ್ನಡ', slug: 'kn', icon: '' },
    { label: 'Kazakh - қазақ тілі', value: 'Kazakh - қазақ тілі', slug: 'kk', icon: '' },
    { label: 'Khmer - ខ្មែរ', value: 'Khmer - ខ្មែរ', slug: 'km', icon: '' },
    { label: 'Korean - 한국어', value: 'Korean - 한국어', slug: 'ko', icon: '' },
    { label: 'Kurdish - Kurdî', value: 'Kurdish - Kurdî', slug: 'ku', icon: '' },
    { label: 'Kyrgyz - кыргызча', value: 'Kyrgyz - кыргызча', slug: 'ky', icon: '' },
    { label: 'Lao - ລາວ', value: 'Lao - ລາວ', slug: 'lo', icon: '' },
    { label: 'Latin', value: 'Latin', slug: 'la', icon: '' },
    { label: 'Latvian - latviešu', value: 'Latvian - latviešu', slug: 'lv', icon: '' },
    { label: 'Lingala - lingála', value: 'Lingala - lingála', slug: 'ln', icon: '' },
    { label: 'Lithuanian - lietuvių', value: 'Lithuanian - lietuvių', slug: 'lt', icon: '' },
    { label: 'Macedonian - македонски', value: 'Macedonian - македонски', slug: 'mk', icon: '' },
    { label: 'Malay - Bahasa Melayu', value: 'Malay - Bahasa Melayu', slug: 'ms', icon: '' },
    { label: 'Malayalam - മലയാളം', value: 'Malayalam - മലയാളം', slug: 'ml', icon: '' },
    { label: 'Maltese - Malti', value: 'Maltese - Malti', slug: 'mt', icon: '' },
    { label: 'Marathi - मराठी', value: 'Marathi - मराठी', slug: 'mr', icon: '' },
    { label: 'Mongolian - монгол', value: 'Mongolian - монгол', slug: 'mn', icon: '' },
    { label: 'Nepali - नेपाली', value: 'Nepali - नेपाली', slug: 'ne', icon: '' },
    { label: 'Norwegian - norsk', value: 'Norwegian - norsk', slug: 'no', icon: '' },
    { label: 'Norwegian Bokmål - norsk bokmål', value: 'Norwegian Bokmål - norsk bokmål', slug: 'nb', icon: '' },
    { label: 'Norwegian Nynorsk - nynorsk', value: 'Norwegian Nynorsk - nynorsk', slug: 'nn', icon: '' },
    { label: 'Occitan', value: 'Occitan', slug: 'oc', icon: '' },
    { label: 'Oriya - ଓଡ଼ିଆ', value: 'Oriya - ଓଡ଼ିଆ', slug: 'or', icon: '' },
    { label: 'Oromo - Oromoo', value: 'Oromo - Oromoo', slug: 'om', icon: '' },
    { label: 'Pashto - پښتو', value: 'Pashto - پښتو', slug: 'ps', icon: '' },
    { label: 'Persian - فارسی', value: 'Persian - فارسی', slug: 'fa', icon: '' },
    { label: 'Polish - polski', value: 'Polish - polski', slug: 'pl', icon: '' },
    { label: 'Portuguese - português', value: 'Portuguese - português', slug: 'pt', icon: '' },
    {
        label: 'Portuguese (Brazil) - português (Brasil)',
        value: 'Portuguese (Brazil) - português (Brasil)',
        slug: 'pt-BR',
        icon: '',
    },
    {
        label: 'Portuguese (Portugal) - português (Portugal)',
        value: 'Portuguese (Portugal) - português (Portugal)',
        slug: 'pt-PT',
        icon: '',
    },
    { label: 'Punjabi - ਪੰਜਾਬੀ', value: 'Punjabi - ਪੰਜਾਬੀ', slug: 'pa', icon: '' },
    { label: 'Quechua', value: 'Quechua', slug: 'qu', icon: '' },
    { label: 'Romanian - română', value: 'Romanian - română', slug: 'ro', icon: '' },
    {
        label: 'Romanian (Moldova) - română (Moldova)',
        value: 'Romanian (Moldova) - română (Moldova)',
        slug: 'mo',
        icon: '',
    },
    { label: 'Romansh - rumantsch', value: 'Romansh - rumantsch', slug: 'rm', icon: '' },
    { label: 'Russian - русский', value: 'Russian - русский', slug: 'ru', icon: '' },
    { label: 'Scottish Gaelic', value: 'Scottish Gaelic', slug: 'gd', icon: '' },
    { label: 'Serbian - српски', value: 'Serbian - српски', slug: 'sr', icon: '' },
    { label: 'Serbo - Croatian', value: 'Serbo - Croatian', slug: 'sh', icon: '' },
    { label: 'Shona - chiShona', value: 'Shona - chiShona', slug: 'sn', icon: '' },
    { label: 'Sindhi', value: 'Sindhi', slug: 'sd', icon: '' },
    { label: 'Sinhala - සිංහල', value: 'Sinhala - සිංහල', slug: 'si', icon: '' },
    { label: 'Slovak - slovenčina', value: 'Slovak - slovenčina', slug: 'sk', icon: '' },
    { label: 'Slovenian - slovenščina', value: 'Slovenian - slovenščina', slug: 'sl', icon: '' },
    { label: 'Somali - Soomaali', value: 'Somali - Soomaali', slug: 'so', icon: '' },
    { label: 'Southern Sotho', value: 'Southern Sotho', slug: 'st', icon: '' },
    { label: 'Spanish - español', value: 'Spanish - español', slug: 'es', icon: '' },
    {
        label: 'Spanish (Argentina) - español (Argentina)',
        value: 'Spanish (Argentina) - español (Argentina)',
        slug: 'es-AR',
        icon: '',
    },
    {
        label: 'Spanish (Latin America) - español (Latinoamérica)',
        value: 'Spanish (Latin America) - español (Latinoamérica)',
        slug: 'es-419',
        icon: '',
    },
    {
        label: 'Spanish (Mexico) - español (México)',
        value: 'Spanish (Mexico) - español (México)',
        slug: 'es-MX',
        icon: '',
    },
    {
        label: 'Spanish (Spain) - español (España)',
        value: 'Spanish (Spain) - español (España)',
        slug: 'es-ES',
        icon: '',
    },
    {
        label: 'Spanish (United States) - español (Estados Unidos)',
        value: 'Spanish (United States) - español (Estados Unidos)',
        slug: 'es-US',
        icon: '',
    },
    { label: 'Sundanese', value: 'Sundanese', slug: 'su', icon: '' },
    { label: 'Swahili - Kiswahili', value: 'Swahili - Kiswahili', slug: 'sw', icon: '' },
    { label: 'Swedish - svenska', value: 'Swedish - svenska', slug: 'sv', icon: '' },
    { label: 'Tajik - тоҷикӣ', value: 'Tajik - тоҷикӣ', slug: 'tg', icon: '' },
    { label: 'Tamil - தமிழ்', value: 'Tamil - தமிழ்', slug: 'ta', icon: '' },
    { label: 'Tatar', value: 'Tatar', slug: 'tt', icon: '' },
    { label: 'Telugu - తెలుగు', value: 'Telugu - తెలుగు', slug: 'te', icon: '' },
    { label: 'Thai - ไทย', value: 'Thai - ไทย', slug: 'th', icon: '' },
    { label: 'Tigrinya - ትግርኛ', value: 'Tigrinya - ትግርኛ', slug: 'ti', icon: '' },
    { label: 'Tongan - lea fakatonga', value: 'Tongan - lea fakatonga', slug: 'to', icon: '' },
    { label: 'Turkish - Türkçe', value: 'Turkish - Türkçe', slug: 'tr', icon: '' },
    { label: 'Turkmen', value: 'Turkmen', slug: 'tk', icon: '' },
    { label: 'Twi', value: 'Twi', slug: 'tw', icon: '' },
    { label: 'Ukrainian - українська', value: 'Ukrainian - українська', slug: 'uk', icon: '' },
    { label: 'Urdu - اردو', value: 'Urdu - اردو', slug: 'ur', icon: '' },
    { label: 'Uyghur', value: 'Uyghur', slug: 'ug', icon: '' },
    { label: 'Uzbek - o‘zbek', value: 'Uzbek - o‘zbek', slug: 'uz', icon: '' },
    { label: 'Vietnamese - Tiếng Việt', value: 'Vietnamese - Tiếng Việt', slug: 'vi', icon: '' },
    { label: 'Walloon - wa', value: 'Walloon - wa', slug: 'wa', icon: '' },
    { label: 'Welsh - Cymraeg', value: 'Welsh - Cymraeg', slug: 'cy', icon: '' },
    { label: 'Western Frisian', value: 'Western Frisian', slug: 'fy', icon: '' },
    { label: 'Xhosa', value: 'Xhosa', slug: 'xh', icon: '' },
    { label: 'Yiddish', value: 'Yiddish', slug: 'yi', icon: '' },
    { label: 'Yoruba - Èdè Yorùbá', value: 'Yoruba - Èdè Yorùbá', slug: 'yo', icon: '' },
    { label: 'Zulu - isiZulu', value: 'Zulu - isiZulu', slug: 'zu', icon: '' },
];

export const timeZoneOptions = [
    { label: 'Africa/Abidjan', value: 'Africa/Abidjan', slug: '', icon: '' },
    { label: 'Africa/Accra', value: 'Africa/Accra', slug: '', icon: '' },
    { label: 'Africa/Addis_Ababa', value: 'Africa/Addis_Ababa', slug: '', icon: '' },
    { label: 'Africa/Algiers', value: 'Africa/Algiers', slug: '', icon: '' },
    { label: 'Africa/Asmara', value: 'Africa/Asmara', slug: '', icon: '' },
    { label: 'Africa/Asmera', value: 'Africa/Asmera', slug: '', icon: '' },
    { label: 'Africa/Bamako', value: 'Africa/Bamako', slug: '', icon: '' },
    { label: 'Africa/Bangui', value: 'Africa/Bangui', slug: '', icon: '' },
    { label: 'Africa/Banjul', value: 'Africa/Banjul', slug: '', icon: '' },
    { label: 'Africa/Bissau', value: 'Africa/Bissau', slug: '', icon: '' },
    { label: 'Africa/Blantyre', value: 'Africa/Blantyre', slug: '', icon: '' },
    { label: 'Africa/Brazzaville', value: 'Africa/Brazzaville', slug: '', icon: '' },
    { label: 'Africa/Bujumbura', value: 'Africa/Bujumbura', slug: '', icon: '' },
    { label: 'Africa/Cairo', value: 'Africa/Cairo', slug: '', icon: '' },
    { label: 'Africa/Casablanca', value: 'Africa/Casablanca', slug: '', icon: '' },
    { label: 'Africa/Ceuta', value: 'Africa/Ceuta', slug: '', icon: '' },
    { label: 'Africa/Conakry', value: 'Africa/Conakry', slug: '', icon: '' },
    { label: 'Africa/Dakar', value: 'Africa/Dakar', slug: '', icon: '' },
    { label: 'Africa/Dar_es_Salaam', value: 'Africa/Dar_es_Salaam', slug: '', icon: '' },
    { label: 'Africa/Djibouti', value: 'Africa/Djibouti', slug: '', icon: '' },
    { label: 'Africa/Douala', value: 'Africa/Douala', slug: '', icon: '' },
    { label: 'Africa/El_Aaiun', value: 'Africa/El_Aaiun', slug: '', icon: '' },
    { label: 'Africa/Freetown', value: 'Africa/Freetown', slug: '', icon: '' },
    { label: 'Africa/Gaborone', value: 'Africa/Gaborone', slug: '', icon: '' },
    { label: 'Africa/Harare', value: 'Africa/Harare', slug: '', icon: '' },
    { label: 'Africa/Johannesburg', value: 'Africa/Johannesburg', slug: '', icon: '' },
    { label: 'Africa/Juba', value: 'Africa/Juba', slug: '', icon: '' },
    { label: 'Africa/Kampala', value: 'Africa/Kampala', slug: '', icon: '' },
    { label: 'Africa/Khartoum', value: 'Africa/Khartoum', slug: '', icon: '' },
    { label: 'Africa/Kigali', value: 'Africa/Kigali', slug: '', icon: '' },
    { label: 'Africa/Kinshasa', value: 'Africa/Kinshasa', slug: '', icon: '' },
    { label: 'Africa/Lagos', value: 'Africa/Lagos', slug: '', icon: '' },
    { label: 'Africa/Libreville', value: 'Africa/Libreville', slug: '', icon: '' },
    { label: 'Africa/Lome', value: 'Africa/Lome', slug: '', icon: '' },
    { label: 'Africa/Luanda', value: 'Africa/Luanda', slug: '', icon: '' },
    { label: 'Africa/Lubumbashi', value: 'Africa/Lubumbashi', slug: '', icon: '' },
    { label: 'Africa/Lusaka', value: 'Africa/Lusaka', slug: '', icon: '' },
    { label: 'Africa/Malabo', value: 'Africa/Malabo', slug: '', icon: '' },
    { label: 'Africa/Maputo', value: 'Africa/Maputo', slug: '', icon: '' },
    { label: 'Africa/Maseru', value: 'Africa/Maseru', slug: '', icon: '' },
    { label: 'Africa/Mbabane', value: 'Africa/Mbabane', slug: '', icon: '' },
    { label: 'Africa/Mogadishu', value: 'Africa/Mogadishu', slug: '', icon: '' },
    { label: 'Africa/Monrovia', value: 'Africa/Monrovia', slug: '', icon: '' },
    { label: 'Africa/Nairobi', value: 'Africa/Nairobi', slug: '', icon: '' },
    { label: 'Africa/Ndjamena', value: 'Africa/Ndjamena', slug: '', icon: '' },
    { label: 'Africa/Niamey', value: 'Africa/Niamey', slug: '', icon: '' },
    { label: 'Africa/Nouakchott', value: 'Africa/Nouakchott', slug: '', icon: '' },
    { label: 'Africa/Ouagadougou', value: 'Africa/Ouagadougou', slug: '', icon: '' },
    { label: 'Africa/Porto-Novo', value: 'Africa/Porto-Novo', slug: '', icon: '' },
    { label: 'Africa/Sao_Tome', value: 'Africa/Sao_Tome', slug: '', icon: '' },
    { label: 'Africa/Timbuktu', value: 'Africa/Timbuktu', slug: '', icon: '' },
    { label: 'Africa/Tripoli', value: 'Africa/Tripoli', slug: '', icon: '' },
    { label: 'Africa/Tunis', value: 'Africa/Tunis', slug: '', icon: '' },
    { label: 'Africa/Windhoek', value: 'Africa/Windhoek', slug: '', icon: '' },
    { label: 'America/Adak', value: 'America/Adak', slug: '', icon: '' },
    { label: 'America/Anchorage', value: 'America/Anchorage', slug: '', icon: '' },
    { label: 'America/Anguilla', value: 'America/Anguilla', slug: '', icon: '' },
    { label: 'America/Antigua', value: 'America/Antigua', slug: '', icon: '' },
    { label: 'America/Araguaina', value: 'America/Araguaina', slug: '', icon: '' },
    { label: 'America/Argentina/Buenos_Aires', value: 'America/Argentina/Buenos_Aires', slug: '', icon: '' },
    { label: 'America/Argentina/Catamarca', value: 'America/Argentina/Catamarca', slug: '', icon: '' },
    { label: 'America/Argentina/ComodRivadavia', value: 'America/Argentina/ComodRivadavia', slug: '', icon: '' },
    { label: 'America/Argentina/Cordoba', value: 'America/Argentina/Cordoba', slug: '', icon: '' },
    { label: 'America/Argentina/Jujuy', value: 'America/Argentina/Jujuy', slug: '', icon: '' },
    { label: 'America/Argentina/La_Rioja', value: 'America/Argentina/La_Rioja', slug: '', icon: '' },
    { label: 'America/Argentina/Mendoza', value: 'America/Argentina/Mendoza', slug: '', icon: '' },
    { label: 'America/Argentina/Rio_Gallegos', value: 'America/Argentina/Rio_Gallegos', slug: '', icon: '' },
    { label: 'America/Argentina/Salta', value: 'America/Argentina/Salta', slug: '', icon: '' },
    { label: 'America/Argentina/San_Juan', value: 'America/Argentina/San_Juan', slug: '', icon: '' },
    { label: 'America/Argentina/San_Luis', value: 'America/Argentina/San_Luis', slug: '', icon: '' },
    { label: 'America/Argentina/Tucuman', value: 'America/Argentina/Tucuman', slug: '', icon: '' },
    { label: 'America/Argentina/Ushuaia', value: 'America/Argentina/Ushuaia', slug: '', icon: '' },
    { label: 'America/Aruba', value: 'America/Aruba', slug: '', icon: '' },
    { label: 'America/Asuncion', value: 'America/Asuncion', slug: '', icon: '' },
    { label: 'America/Atikokan', value: 'America/Atikokan', slug: '', icon: '' },
    { label: 'America/Atka', value: 'America/Atka', slug: '', icon: '' },
    { label: 'America/Bahia', value: 'America/Bahia', slug: '', icon: '' },
    { label: 'America/Bahia_Banderas', value: 'America/Bahia_Banderas', slug: '', icon: '' },
    { label: 'America/Barbados', value: 'America/Barbados', slug: '', icon: '' },
    { label: 'America/Belem', value: 'America/Belem', slug: '', icon: '' },
    { label: 'America/Belize', value: 'America/Belize', slug: '', icon: '' },
    { label: 'America/Blanc-Sablon', value: 'America/Blanc-Sablon', slug: '', icon: '' },
    { label: 'America/Boa_Vista', value: 'America/Boa_Vista', slug: '', icon: '' },
    { label: 'America/Bogota', value: 'America/Bogota', slug: '', icon: '' },
    { label: 'America/Boise', value: 'America/Boise', slug: '', icon: '' },
    { label: 'America/Buenos_Aires', value: 'America/Buenos_Aires', slug: '', icon: '' },
    { label: 'America/Cambridge_Bay', value: 'America/Cambridge_Bay', slug: '', icon: '' },
    { label: 'America/Campo_Grande', value: 'America/Campo_Grande', slug: '', icon: '' },
    { label: 'America/Cancun', value: 'America/Cancun', slug: '', icon: '' },
    { label: 'America/Caracas', value: 'America/Caracas', slug: '', icon: '' },
    { label: 'America/Catamarca', value: 'America/Catamarca', slug: '', icon: '' },
    { label: 'America/Cayenne', value: 'America/Cayenne', slug: '', icon: '' },
    { label: 'America/Cayman', value: 'America/Cayman', slug: '', icon: '' },
    { label: 'America/Chicago', value: 'America/Chicago', slug: '', icon: '' },
    { label: 'America/Chihuahua', value: 'America/Chihuahua', slug: '', icon: '' },
    { label: 'America/Coral_Harbour', value: 'America/Coral_Harbour', slug: '', icon: '' },
    { label: 'America/Cordoba', value: 'America/Cordoba', slug: '', icon: '' },
    { label: 'America/Costa_Rica', value: 'America/Costa_Rica', slug: '', icon: '' },
    { label: 'America/Creston', value: 'America/Creston', slug: '', icon: '' },
    { label: 'America/Cuiaba', value: 'America/Cuiaba', slug: '', icon: '' },
    { label: 'America/Curacao', value: 'America/Curacao', slug: '', icon: '' },
    { label: 'America/Danmarkshavn', value: 'America/Danmarkshavn', slug: '', icon: '' },
    { label: 'America/Dawson', value: 'America/Dawson', slug: '', icon: '' },
    { label: 'America/Dawson_Creek', value: 'America/Dawson_Creek', slug: '', icon: '' },
    { label: 'America/Denver', value: 'America/Denver', slug: '', icon: '' },
    { label: 'America/Detroit', value: 'America/Detroit', slug: '', icon: '' },
    { label: 'America/Dominica', value: 'America/Dominica', slug: '', icon: '' },
    { label: 'America/Edmonton', value: 'America/Edmonton', slug: '', icon: '' },
    { label: 'America/Eirunepe', value: 'America/Eirunepe', slug: '', icon: '' },
    { label: 'America/El_Salvador', value: 'America/El_Salvador', slug: '', icon: '' },
    { label: 'America/Ensenada', value: 'America/Ensenada', slug: '', icon: '' },
    { label: 'America/Fort_Nelson', value: 'America/Fort_Nelson', slug: '', icon: '' },
    { label: 'America/Fort_Wayne', value: 'America/Fort_Wayne', slug: '', icon: '' },
    { label: 'America/Fortaleza', value: 'America/Fortaleza', slug: '', icon: '' },
    { label: 'America/Glace_Bay', value: 'America/Glace_Bay', slug: '', icon: '' },
    { label: 'America/Godthab', value: 'America/Godthab', slug: '', icon: '' },
    { label: 'America/Goose_Bay', value: 'America/Goose_Bay', slug: '', icon: '' },
    { label: 'America/Grand_Turk', value: 'America/Grand_Turk', slug: '', icon: '' },
    { label: 'America/Grenada', value: 'America/Grenada', slug: '', icon: '' },
    { label: 'America/Guadeloupe', value: 'America/Guadeloupe', slug: '', icon: '' },
    { label: 'America/Guatemala', value: 'America/Guatemala', slug: '', icon: '' },
    { label: 'America/Guayaquil', value: 'America/Guayaquil', slug: '', icon: '' },
    { label: 'America/Guyana', value: 'America/Guyana', slug: '', icon: '' },
    { label: 'America/Halifax', value: 'America/Halifax', slug: '', icon: '' },
    { label: 'America/Havana', value: 'America/Havana', slug: '', icon: '' },
    { label: 'America/Hermosillo', value: 'America/Hermosillo', slug: '', icon: '' },
    { label: 'America/Indiana/Indianapolis', value: 'America/Indiana/Indianapolis', slug: '', icon: '' },
    { label: 'America/Indiana/Knox', value: 'America/Indiana/Knox', slug: '', icon: '' },
    { label: 'America/Indiana/Marengo', value: 'America/Indiana/Marengo', slug: '', icon: '' },
    { label: 'America/Indiana/Petersburg', value: 'America/Indiana/Petersburg', slug: '', icon: '' },
    { label: 'America/Indiana/Tell_City', value: 'America/Indiana/Tell_City', slug: '', icon: '' },
    { label: 'America/Indiana/Vevay', value: 'America/Indiana/Vevay', slug: '', icon: '' },
    { label: 'America/Indiana/Vincennes', value: 'America/Indiana/Vincennes', slug: '', icon: '' },
    { label: 'America/Indiana/Winamac', value: 'America/Indiana/Winamac', slug: '', icon: '' },
    { label: 'America/Indianapolis', value: 'America/Indianapolis', slug: '', icon: '' },
    { label: 'America/Inuvik', value: 'America/Inuvik', slug: '', icon: '' },
    { label: 'America/Iqaluit', value: 'America/Iqaluit', slug: '', icon: '' },
    { label: 'America/Jamaica', value: 'America/Jamaica', slug: '', icon: '' },
    { label: 'America/Jujuy', value: 'America/Jujuy', slug: '', icon: '' },
    { label: 'America/Juneau', value: 'America/Juneau', slug: '', icon: '' },
    { label: 'America/Kentucky/Louisville', value: 'America/Kentucky/Louisville', slug: '', icon: '' },
    { label: 'America/Kentucky/Monticello', value: 'America/Kentucky/Monticello', slug: '', icon: '' },
    { label: 'America/Knox_IN', value: 'America/Knox_IN', slug: '', icon: '' },
    { label: 'America/Kralendijk', value: 'America/Kralendijk', slug: '', icon: '' },
    { label: 'America/La_Paz', value: 'America/La_Paz', slug: '', icon: '' },
    { label: 'America/Lima', value: 'America/Lima', slug: '', icon: '' },
    { label: 'America/Los_Angeles', value: 'America/Los_Angeles', slug: '', icon: '' },
    { label: 'America/Louisville', value: 'America/Louisville', slug: '', icon: '' },
    { label: 'America/Lower_Princes', value: 'America/Lower_Princes', slug: '', icon: '' },
    { label: 'America/Maceio', value: 'America/Maceio', slug: '', icon: '' },
    { label: 'America/Managua', value: 'America/Managua', slug: '', icon: '' },
    { label: 'America/Manaus', value: 'America/Manaus', slug: '', icon: '' },
    { label: 'America/Marigot', value: 'America/Marigot', slug: '', icon: '' },
    { label: 'America/Martinique', value: 'America/Martinique', slug: '', icon: '' },
    { label: 'America/Matamoros', value: 'America/Matamoros', slug: '', icon: '' },
    { label: 'America/Mazatlan', value: 'America/Mazatlan', slug: '', icon: '' },
    { label: 'America/Mendoza', value: 'America/Mendoza', slug: '', icon: '' },
    { label: 'America/Menominee', value: 'America/Menominee', slug: '', icon: '' },
    { label: 'America/Merida', value: 'America/Merida', slug: '', icon: '' },
    { label: 'America/Metlakatla', value: 'America/Metlakatla', slug: '', icon: '' },
    { label: 'America/Mexico_City', value: 'America/Mexico_City', slug: '', icon: '' },
    { label: 'America/Miquelon', value: 'America/Miquelon', slug: '', icon: '' },
    { label: 'America/Moncton', value: 'America/Moncton', slug: '', icon: '' },
    { label: 'America/Monterrey', value: 'America/Monterrey', slug: '', icon: '' },
    { label: 'America/Montevideo', value: 'America/Montevideo', slug: '', icon: '' },
    { label: 'America/Montreal', value: 'America/Montreal', slug: '', icon: '' },
    { label: 'America/Montserrat', value: 'America/Montserrat', slug: '', icon: '' },
    { label: 'America/Nassau', value: 'America/Nassau', slug: '', icon: '' },
    { label: 'America/New_York', value: 'America/New_York', slug: '', icon: '' },
    { label: 'America/Nipigon', value: 'America/Nipigon', slug: '', icon: '' },
    { label: 'America/Nome', value: 'America/Nome', slug: '', icon: '' },
    { label: 'America/Noronha', value: 'America/Noronha', slug: '', icon: '' },
    { label: 'America/North_Dakota/Beulah', value: 'America/North_Dakota/Beulah', slug: '', icon: '' },
    { label: 'America/North_Dakota/Center', value: 'America/North_Dakota/Center', slug: '', icon: '' },
    { label: 'America/North_Dakota/New_Salem', value: 'America/North_Dakota/New_Salem', slug: '', icon: '' },
    { label: 'America/Nuuk', value: 'America/Nuuk', slug: '', icon: '' },
    { label: 'America/Ojinaga', value: 'America/Ojinaga', slug: '', icon: '' },
    { label: 'America/Panama', value: 'America/Panama', slug: '', icon: '' },
    { label: 'America/Pangnirtung', value: 'America/Pangnirtung', slug: '', icon: '' },
    { label: 'America/Paramaribo', value: 'America/Paramaribo', slug: '', icon: '' },
    { label: 'America/Phoenix', value: 'America/Phoenix', slug: '', icon: '' },
    { label: 'America/Port-au-Prince', value: 'America/Port-au-Prince', slug: '', icon: '' },
    { label: 'America/Port_of_Spain', value: 'America/Port_of_Spain', slug: '', icon: '' },
    { label: 'America/Porto_Acre', value: 'America/Porto_Acre', slug: '', icon: '' },
    { label: 'America/Porto_Velho', value: 'America/Porto_Velho', slug: '', icon: '' },
    { label: 'America/Puerto_Rico', value: 'America/Puerto_Rico', slug: '', icon: '' },
    { label: 'America/Punta_Arenas', value: 'America/Punta_Arenas', slug: '', icon: '' },
    { label: 'America/Rainy_River', value: 'America/Rainy_River', slug: '', icon: '' },
    { label: 'America/Rankin_Inlet', value: 'America/Rankin_Inlet', slug: '', icon: '' },
    { label: 'America/Recife', value: 'America/Recife', slug: '', icon: '' },
    { label: 'America/Regina', value: 'America/Regina', slug: '', icon: '' },
    { label: 'America/Resolute', value: 'America/Resolute', slug: '', icon: '' },
    { label: 'America/Rio_Branco', value: 'America/Rio_Branco', slug: '', icon: '' },
    { label: 'America/Rosario', value: 'America/Rosario', slug: '', icon: '' },
    { label: 'America/Santa_Isabel', value: 'America/Santa_Isabel', slug: '', icon: '' },
    { label: 'America/Santarem', value: 'America/Santarem', slug: '', icon: '' },
    { label: 'America/Santiago', value: 'America/Santiago', slug: '', icon: '' },
    { label: 'America/Santo_Domingo', value: 'America/Santo_Domingo', slug: '', icon: '' },
    { label: 'America/Sao_Paulo', value: 'America/Sao_Paulo', slug: '', icon: '' },
    { label: 'America/Scoresbysund', value: 'America/Scoresbysund', slug: '', icon: '' },
    { label: 'America/Shiprock', value: 'America/Shiprock', slug: '', icon: '' },
    { label: 'America/Sitka', value: 'America/Sitka', slug: '', icon: '' },
    { label: 'America/St_Barthelemy', value: 'America/St_Barthelemy', slug: '', icon: '' },
    { label: 'America/St_Johns', value: 'America/St_Johns', slug: '', icon: '' },
    { label: 'America/St_Kitts', value: 'America/St_Kitts', slug: '', icon: '' },
    { label: 'America/St_Lucia', value: 'America/St_Lucia', slug: '', icon: '' },
    { label: 'America/St_Thomas', value: 'America/St_Thomas', slug: '', icon: '' },
    { label: 'America/St_Vincent', value: 'America/St_Vincent', slug: '', icon: '' },
    { label: 'America/Swift_Current', value: 'America/Swift_Current', slug: '', icon: '' },
    { label: 'America/Tegucigalpa', value: 'America/Tegucigalpa', slug: '', icon: '' },
    { label: 'America/Thule', value: 'America/Thule', slug: '', icon: '' },
    { label: 'America/Thunder_Bay', value: 'America/Thunder_Bay', slug: '', icon: '' },
    { label: 'America/Tijuana', value: 'America/Tijuana', slug: '', icon: '' },
    { label: 'America/Toronto', value: 'America/Toronto', slug: '', icon: '' },
    { label: 'America/Tortola', value: 'America/Tortola', slug: '', icon: '' },
    { label: 'America/Vancouver', value: 'America/Vancouver', slug: '', icon: '' },
    { label: 'America/Virgin', value: 'America/Virgin', slug: '', icon: '' },
    { label: 'America/Whitehorse', value: 'America/Whitehorse', slug: '', icon: '' },
    { label: 'America/Winnipeg', value: 'America/Winnipeg', slug: '', icon: '' },
    { label: 'America/Yakutat', value: 'America/Yakutat', slug: '', icon: '' },
    { label: 'America/Yellowknife', value: 'America/Yellowknife', slug: '', icon: '' },
    { label: 'Antarctica/Casey', value: 'Antarctica/Casey', slug: '', icon: '' },
    { label: 'Antarctica/Davis', value: 'Antarctica/Davis', slug: '', icon: '' },
    { label: 'Antarctica/DumontDUrville', value: 'Antarctica/DumontDUrville', slug: '', icon: '' },
    { label: 'Antarctica/Macquarie', value: 'Antarctica/Macquarie', slug: '', icon: '' },
    { label: 'Antarctica/Mawson', value: 'Antarctica/Mawson', slug: '', icon: '' },
    { label: 'Antarctica/McMurdo', value: 'Antarctica/McMurdo', slug: '', icon: '' },
    { label: 'Antarctica/Palmer', value: 'Antarctica/Palmer', slug: '', icon: '' },
    { label: 'Antarctica/Rothera', value: 'Antarctica/Rothera', slug: '', icon: '' },
    { label: 'Antarctica/South_Pole', value: 'Antarctica/South_Pole', slug: '', icon: '' },
    { label: 'Antarctica/Syowa', value: 'Antarctica/Syowa', slug: '', icon: '' },
    { label: 'Antarctica/Troll', value: 'Antarctica/Troll', slug: '', icon: '' },
    { label: 'Antarctica/Vostok', value: 'Antarctica/Vostok', slug: '', icon: '' },
    { label: 'Arctic/Longyearbyen', value: 'Arctic/Longyearbyen', slug: '', icon: '' },
    { label: 'Asia/Aden', value: 'Asia/Aden', slug: '', icon: '' },
    { label: 'Asia/Almaty', value: 'Asia/Almaty', slug: '', icon: '' },
    { label: 'Asia/Amman', value: 'Asia/Amman', slug: '', icon: '' },
    { label: 'Asia/Anadyr', value: 'Asia/Anadyr', slug: '', icon: '' },
    { label: 'Asia/Aqtau', value: 'Asia/Aqtau', slug: '', icon: '' },
    { label: 'Asia/Aqtobe', value: 'Asia/Aqtobe', slug: '', icon: '' },
    { label: 'Asia/Ashgabat', value: 'Asia/Ashgabat', slug: '', icon: '' },
    { label: 'Asia/Ashkhabad', value: 'Asia/Ashkhabad', slug: '', icon: '' },
    { label: 'Asia/Atyrau', value: 'Asia/Atyrau', slug: '', icon: '' },
    { label: 'Asia/Baghdad', value: 'Asia/Baghdad', slug: '', icon: '' },
    { label: 'Asia/Bahrain', value: 'Asia/Bahrain', slug: '', icon: '' },
    { label: 'Asia/Baku', value: 'Asia/Baku', slug: '', icon: '' },
    { label: 'Asia/Bangkok', value: 'Asia/Bangkok', slug: '', icon: '' },
    { label: 'Asia/Barnaul', value: 'Asia/Barnaul', slug: '', icon: '' },
    { label: 'Asia/Beirut', value: 'Asia/Beirut', slug: '', icon: '' },
    { label: 'Asia/Bishkek', value: 'Asia/Bishkek', slug: '', icon: '' },
    { label: 'Asia/Brunei', value: 'Asia/Brunei', slug: '', icon: '' },
    { label: 'Asia/Calcutta', value: 'Asia/Calcutta', slug: '', icon: '' },
    { label: 'Asia/Chita', value: 'Asia/Chita', slug: '', icon: '' },
    { label: 'Asia/Choibalsan', value: 'Asia/Choibalsan', slug: '', icon: '' },
    { label: 'Asia/Chongqing', value: 'Asia/Chongqing', slug: '', icon: '' },
    { label: 'Asia/Chungking', value: 'Asia/Chungking', slug: '', icon: '' },
    { label: 'Asia/Colombo', value: 'Asia/Colombo', slug: '', icon: '' },
    { label: 'Asia/Dacca', value: 'Asia/Dacca', slug: '', icon: '' },
    { label: 'Asia/Damascus', value: 'Asia/Damascus', slug: '', icon: '' },
    { label: 'Asia/Dhaka', value: 'Asia/Dhaka', slug: '', icon: '' },
    { label: 'Asia/Dili', value: 'Asia/Dili', slug: '', icon: '' },
    { label: 'Asia/Dubai', value: 'Asia/Dubai', slug: '', icon: '' },
    { label: 'Asia/Dushanbe', value: 'Asia/Dushanbe', slug: '', icon: '' },
    { label: 'Asia/Famagusta', value: 'Asia/Famagusta', slug: '', icon: '' },
    { label: 'Asia/Gaza', value: 'Asia/Gaza', slug: '', icon: '' },
    { label: 'Asia/Harbin', value: 'Asia/Harbin', slug: '', icon: '' },
    { label: 'Asia/Hebron', value: 'Asia/Hebron', slug: '', icon: '' },
    { label: 'Asia/Ho_Chi_Minh', value: 'Asia/Ho_Chi_Minh', slug: '', icon: '' },
    { label: 'Asia/Hong_Kong', value: 'Asia/Hong_Kong', slug: '', icon: '' },
    { label: 'Asia/Hovd', value: 'Asia/Hovd', slug: '', icon: '' },
    { label: 'Asia/Irkutsk', value: 'Asia/Irkutsk', slug: '', icon: '' },
    { label: 'Asia/Istanbul', value: 'Asia/Istanbul', slug: '', icon: '' },
    { label: 'Asia/Jakarta', value: 'Asia/Jakarta', slug: '', icon: '' },
    { label: 'Asia/Jayapura', value: 'Asia/Jayapura', slug: '', icon: '' },
    { label: 'Asia/Jerusalem', value: 'Asia/Jerusalem', slug: '', icon: '' },
    { label: 'Asia/Kabul', value: 'Asia/Kabul', slug: '', icon: '' },
    { label: 'Asia/Kamchatka', value: 'Asia/Kamchatka', slug: '', icon: '' },
    { label: 'Asia/Karachi', value: 'Asia/Karachi', slug: '', icon: '' },
    { label: 'Asia/Kashgar', value: 'Asia/Kashgar', slug: '', icon: '' },
    { label: 'Asia/Kathmandu', value: 'Asia/Kathmandu', slug: '', icon: '' },
    { label: 'Asia/Katmandu', value: 'Asia/Katmandu', slug: '', icon: '' },
    { label: 'Asia/Khandyga', value: 'Asia/Khandyga', slug: '', icon: '' },
    { label: 'Asia/Kolkata', value: 'Asia/Kolkata', slug: '', icon: '' },
    { label: 'Asia/Krasnoyarsk', value: 'Asia/Krasnoyarsk', slug: '', icon: '' },
    { label: 'Asia/Kuala_Lumpur', value: 'Asia/Kuala_Lumpur', slug: '', icon: '' },
    { label: 'Asia/Kuching', value: 'Asia/Kuching', slug: '', icon: '' },
    { label: 'Asia/Kuwait', value: 'Asia/Kuwait', slug: '', icon: '' },
    { label: 'Asia/Macao', value: 'Asia/Macao', slug: '', icon: '' },
    { label: 'Asia/Macau', value: 'Asia/Macau', slug: '', icon: '' },
    { label: 'Asia/Magadan', value: 'Asia/Magadan', slug: '', icon: '' },
    { label: 'Asia/Makassar', value: 'Asia/Makassar', slug: '', icon: '' },
    { label: 'Asia/Manila', value: 'Asia/Manila', slug: '', icon: '' },
    { label: 'Asia/Muscat', value: 'Asia/Muscat', slug: '', icon: '' },
    { label: 'Asia/Nicosia', value: 'Asia/Nicosia', slug: '', icon: '' },
    { label: 'Asia/Novokuznetsk', value: 'Asia/Novokuznetsk', slug: '', icon: '' },
    { label: 'Asia/Novosibirsk', value: 'Asia/Novosibirsk', slug: '', icon: '' },
    { label: 'Asia/Omsk', value: 'Asia/Omsk', slug: '', icon: '' },
    { label: 'Asia/Oral', value: 'Asia/Oral', slug: '', icon: '' },
    { label: 'Asia/Phnom_Penh', value: 'Asia/Phnom_Penh', slug: '', icon: '' },
    { label: 'Asia/Pontianak', value: 'Asia/Pontianak', slug: '', icon: '' },
    { label: 'Asia/Pyongyang', value: 'Asia/Pyongyang', slug: '', icon: '' },
    { label: 'Asia/Qatar', value: 'Asia/Qatar', slug: '', icon: '' },
    { label: 'Asia/Qostanay', value: 'Asia/Qostanay', slug: '', icon: '' },
    { label: 'Asia/Qyzylorda', value: 'Asia/Qyzylorda', slug: '', icon: '' },
    { label: 'Asia/Rangoon', value: 'Asia/Rangoon', slug: '', icon: '' },
    { label: 'Asia/Riyadh', value: 'Asia/Riyadh', slug: '', icon: '' },
    { label: 'Asia/Saigon', value: 'Asia/Saigon', slug: '', icon: '' },
    { label: 'Asia/Sakhalin', value: 'Asia/Sakhalin', slug: '', icon: '' },
    { label: 'Asia/Samarkand', value: 'Asia/Samarkand', slug: '', icon: '' },
    { label: 'Asia/Seoul', value: 'Asia/Seoul', slug: '', icon: '' },
    { label: 'Asia/Shanghai', value: 'Asia/Shanghai', slug: '', icon: '' },
    { label: 'Asia/Singapore', value: 'Asia/Singapore', slug: '', icon: '' },
    { label: 'Asia/Srednekolymsk', value: 'Asia/Srednekolymsk', slug: '', icon: '' },
    { label: 'Asia/Taipei', value: 'Asia/Taipei', slug: '', icon: '' },
    { label: 'Asia/Tashkent', value: 'Asia/Tashkent', slug: '', icon: '' },
    { label: 'Asia/Tbilisi', value: 'Asia/Tbilisi', slug: '', icon: '' },
    { label: 'Asia/Tehran', value: 'Asia/Tehran', slug: '', icon: '' },
    { label: 'Asia/Tel_Aviv', value: 'Asia/Tel_Aviv', slug: '', icon: '' },
    { label: 'Asia/Thimbu', value: 'Asia/Thimbu', slug: '', icon: '' },
    { label: 'Asia/Thimphu', value: 'Asia/Thimphu', slug: '', icon: '' },
    { label: 'Asia/Tokyo', value: 'Asia/Tokyo', slug: '', icon: '' },
    { label: 'Asia/Tomsk', value: 'Asia/Tomsk', slug: '', icon: '' },
    { label: 'Asia/Ujung_Pandang', value: 'Asia/Ujung_Pandang', slug: '', icon: '' },
    { label: 'Asia/Ulaanbaatar', value: 'Asia/Ulaanbaatar', slug: '', icon: '' },
    { label: 'Asia/Ulan_Bator', value: 'Asia/Ulan_Bator', slug: '', icon: '' },
    { label: 'Asia/Urumqi', value: 'Asia/Urumqi', slug: '', icon: '' },
    { label: 'Asia/Ust-Nera', value: 'Asia/Ust-Nera', slug: '', icon: '' },
    { label: 'Asia/Vientiane', value: 'Asia/Vientiane', slug: '', icon: '' },
    { label: 'Asia/Vladivostok', value: 'Asia/Vladivostok', slug: '', icon: '' },
    { label: 'Asia/Yakutsk', value: 'Asia/Yakutsk', slug: '', icon: '' },
    { label: 'Asia/Yangon', value: 'Asia/Yangon', slug: '', icon: '' },
    { label: 'Asia/Yekaterinburg', value: 'Asia/Yekaterinburg', slug: '', icon: '' },
    { label: 'Asia/Yerevan', value: 'Asia/Yerevan', slug: '', icon: '' },
    { label: 'Atlantic/Azores', value: 'Atlantic/Azores', slug: '', icon: '' },
    { label: 'Atlantic/Bermuda', value: 'Atlantic/Bermuda', slug: '', icon: '' },
    { label: 'Atlantic/Canary', value: 'Atlantic/Canary', slug: '', icon: '' },
    { label: 'Atlantic/Cape_Verde', value: 'Atlantic/Cape_Verde', slug: '', icon: '' },
    { label: 'Atlantic/Faeroe', value: 'Atlantic/Faeroe', slug: '', icon: '' },
    { label: 'Atlantic/Faroe', value: 'Atlantic/Faroe', slug: '', icon: '' },
    { label: 'Atlantic/Jan_Mayen', value: 'Atlantic/Jan_Mayen', slug: '', icon: '' },
    { label: 'Atlantic/Madeira', value: 'Atlantic/Madeira', slug: '', icon: '' },
    { label: 'Atlantic/Reykjavik', value: 'Atlantic/Reykjavik', slug: '', icon: '' },
    { label: 'Atlantic/South_Georgia', value: 'Atlantic/South_Georgia', slug: '', icon: '' },
    { label: 'Atlantic/St_Helena', value: 'Atlantic/St_Helena', slug: '', icon: '' },
    { label: 'Atlantic/Stanley', value: 'Atlantic/Stanley', slug: '', icon: '' },
    { label: 'Australia/ACT', value: 'Australia/ACT', slug: '', icon: '' },
    { label: 'Australia/Adelaide', value: 'Australia/Adelaide', slug: '', icon: '' },
    { label: 'Australia/Brisbane', value: 'Australia/Brisbane', slug: '', icon: '' },
    { label: 'Australia/Broken_Hill', value: 'Australia/Broken_Hill', slug: '', icon: '' },
    { label: 'Australia/Canberra', value: 'Australia/Canberra', slug: '', icon: '' },
    { label: 'Australia/Currie', value: 'Australia/Currie', slug: '', icon: '' },
    { label: 'Australia/Darwin', value: 'Australia/Darwin', slug: '', icon: '' },
    { label: 'Australia/Eucla', value: 'Australia/Eucla', slug: '', icon: '' },
    { label: 'Australia/Hobart', value: 'Australia/Hobart', slug: '', icon: '' },
    { label: 'Australia/LHI', value: 'Australia/LHI', slug: '', icon: '' },
    { label: 'Australia/Lindeman', value: 'Australia/Lindeman', slug: '', icon: '' },
    { label: 'Australia/Lord_Howe', value: 'Australia/Lord_Howe', slug: '', icon: '' },
    { label: 'Australia/Melbourne', value: 'Australia/Melbourne', slug: '', icon: '' },
    { label: 'Australia/NSW', value: 'Australia/NSW', slug: '', icon: '' },
    { label: 'Australia/North', value: 'Australia/North', slug: '', icon: '' },
    { label: 'Australia/Perth', value: 'Australia/Perth', slug: '', icon: '' },
    { label: 'Australia/Queensland', value: 'Australia/Queensland', slug: '', icon: '' },
    { label: 'Australia/South', value: 'Australia/South', slug: '', icon: '' },
    { label: 'Australia/Sydney', value: 'Australia/Sydney', slug: '', icon: '' },
    { label: 'Australia/Tasmania', value: 'Australia/Tasmania', slug: '', icon: '' },
    { label: 'Australia/Victoria', value: 'Australia/Victoria', slug: '', icon: '' },
    { label: 'Australia/West', value: 'Australia/West', slug: '', icon: '' },
    { label: 'Australia/Yancowinna', value: 'Australia/Yancowinna', slug: '', icon: '' },
    { label: 'Brazil/Acre', value: 'Brazil/Acre', slug: '', icon: '' },
    { label: 'Brazil/DeNoronha', value: 'Brazil/DeNoronha', slug: '', icon: '' },
    { label: 'Brazil/East', value: 'Brazil/East', slug: '', icon: '' },
    { label: 'Brazil/West', value: 'Brazil/West', slug: '', icon: '' },
    { label: 'CET', value: 'CET', slug: '', icon: '' },
    { label: 'CST6CDT', value: 'CST6CDT', slug: '', icon: '' },
    { label: 'Canada/Atlantic', value: 'Canada/Atlantic', slug: '', icon: '' },
    { label: 'Canada/Central', value: 'Canada/Central', slug: '', icon: '' },
    { label: 'Canada/Eastern', value: 'Canada/Eastern', slug: '', icon: '' },
    { label: 'Canada/Mountain', value: 'Canada/Mountain', slug: '', icon: '' },
    { label: 'Canada/Newfoundland', value: 'Canada/Newfoundland', slug: '', icon: '' },
    { label: 'Canada/Pacific', value: 'Canada/Pacific', slug: '', icon: '' },
    { label: 'Canada/Saskatchewan', value: 'Canada/Saskatchewan', slug: '', icon: '' },
    { label: 'Canada/Yukon', value: 'Canada/Yukon', slug: '', icon: '' },
    { label: 'Chile/Continental', value: 'Chile/Continental', slug: '', icon: '' },
    { label: 'Chile/EasterIsland', value: 'Chile/EasterIsland', slug: '', icon: '' },
    { label: 'Cuba', value: 'Cuba', slug: '', icon: '' },
    { label: 'EET', value: 'EET', slug: '', icon: '' },
    { label: 'EST', value: 'EST', slug: '', icon: '' },
    { label: 'EST5EDT', value: 'EST5EDT', slug: '', icon: '' },
    { label: 'Egypt', value: 'Egypt', slug: '', icon: '' },
    { label: 'Eire', value: 'Eire', slug: '', icon: '' },
    { label: 'Etc/GMT', value: 'Etc/GMT', slug: '', icon: '' },
    { label: 'Etc/GMT+0', value: 'Etc/GMT+0', slug: '', icon: '' },
    { label: 'Etc/GMT+1', value: 'Etc/GMT+1', slug: '', icon: '' },
    { label: 'Etc/GMT+10', value: 'Etc/GMT+10', slug: '', icon: '' },
    { label: 'Etc/GMT+11', value: 'Etc/GMT+11', slug: '', icon: '' },
    { label: 'Etc/GMT+12', value: 'Etc/GMT+12', slug: '', icon: '' },
    { label: 'Etc/GMT+2', value: 'Etc/GMT+2', slug: '', icon: '' },
    { label: 'Etc/GMT+3', value: 'Etc/GMT+3', slug: '', icon: '' },
    { label: 'Etc/GMT+4', value: 'Etc/GMT+4', slug: '', icon: '' },
    { label: 'Etc/GMT+5', value: 'Etc/GMT+5', slug: '', icon: '' },
    { label: 'Etc/GMT+6', value: 'Etc/GMT+6', slug: '', icon: '' },
    { label: 'Etc/GMT+7', value: 'Etc/GMT+7', slug: '', icon: '' },
    { label: 'Etc/GMT+8', value: 'Etc/GMT+8', slug: '', icon: '' },
    { label: 'Etc/GMT+9', value: 'Etc/GMT+9', slug: '', icon: '' },
    { label: 'Etc/GMT-0', value: 'Etc/GMT-0', slug: '', icon: '' },
    { label: 'Etc/GMT-1', value: 'Etc/GMT-1', slug: '', icon: '' },
    { label: 'Etc/GMT-10', value: 'Etc/GMT-10', slug: '', icon: '' },
    { label: 'Etc/GMT-11', value: 'Etc/GMT-11', slug: '', icon: '' },
    { label: 'Etc/GMT-12', value: 'Etc/GMT-12', slug: '', icon: '' },
    { label: 'Etc/GMT-13', value: 'Etc/GMT-13', slug: '', icon: '' },
    { label: 'Etc/GMT-14', value: 'Etc/GMT-14', slug: '', icon: '' },
    { label: 'Etc/GMT-2', value: 'Etc/GMT-2', slug: '', icon: '' },
    { label: 'Etc/GMT-3', value: 'Etc/GMT-3', slug: '', icon: '' },
    { label: 'Etc/GMT-4', value: 'Etc/GMT-4', slug: '', icon: '' },
    { label: 'Etc/GMT-5', value: 'Etc/GMT-5', slug: '', icon: '' },
    { label: 'Etc/GMT-6', value: 'Etc/GMT-6', slug: '', icon: '' },
    { label: 'Etc/GMT-7', value: 'Etc/GMT-7', slug: '', icon: '' },
    { label: 'Etc/GMT-8', value: 'Etc/GMT-8', slug: '', icon: '' },
    { label: 'Etc/GMT-9', value: 'Etc/GMT-9', slug: '', icon: '' },
    { label: 'Etc/GMT0', value: 'Etc/GMT0', slug: '', icon: '' },
    { label: 'Etc/Greenwich', value: 'Etc/Greenwich', slug: '', icon: '' },
    { label: 'Etc/UCT', value: 'Etc/UCT', slug: '', icon: '' },
    { label: 'Etc/UTC', value: 'Etc/UTC', slug: '', icon: '' },
    { label: 'Etc/Universal', value: 'Etc/Universal', slug: '', icon: '' },
    { label: 'Etc/Zulu', value: 'Etc/Zulu', slug: '', icon: '' },
    { label: 'Europe/Amsterdam', value: 'Europe/Amsterdam', slug: '', icon: '' },
    { label: 'Europe/Andorra', value: 'Europe/Andorra', slug: '', icon: '' },
    { label: 'Europe/Astrakhan', value: 'Europe/Astrakhan', slug: '', icon: '' },
    { label: 'Europe/Athens', value: 'Europe/Athens', slug: '', icon: '' },
    { label: 'Europe/Belfast', value: 'Europe/Belfast', slug: '', icon: '' },
    { label: 'Europe/Belgrade', value: 'Europe/Belgrade', slug: '', icon: '' },
    { label: 'Europe/Berlin', value: 'Europe/Berlin', slug: '', icon: '' },
    { label: 'Europe/Bratislava', value: 'Europe/Bratislava', slug: '', icon: '' },
    { label: 'Europe/Brussels', value: 'Europe/Brussels', slug: '', icon: '' },
    { label: 'Europe/Bucharest', value: 'Europe/Bucharest', slug: '', icon: '' },
    { label: 'Europe/Budapest', value: 'Europe/Budapest', slug: '', icon: '' },
    { label: 'Europe/Busingen', value: 'Europe/Busingen', slug: '', icon: '' },
    { label: 'Europe/Chisinau', value: 'Europe/Chisinau', slug: '', icon: '' },
    { label: 'Europe/Copenhagen', value: 'Europe/Copenhagen', slug: '', icon: '' },
    { label: 'Europe/Dublin', value: 'Europe/Dublin', slug: '', icon: '' },
    { label: 'Europe/Gibraltar', value: 'Europe/Gibraltar', slug: '', icon: '' },
    { label: 'Europe/Guernsey', value: 'Europe/Guernsey', slug: '', icon: '' },
    { label: 'Europe/Helsinki', value: 'Europe/Helsinki', slug: '', icon: '' },
    { label: 'Europe/Isle_of_Man', value: 'Europe/Isle_of_Man', slug: '', icon: '' },
    { label: 'Europe/Istanbul', value: 'Europe/Istanbul', slug: '', icon: '' },
    { label: 'Europe/Jersey', value: 'Europe/Jersey', slug: '', icon: '' },
    { label: 'Europe/Kaliningrad', value: 'Europe/Kaliningrad', slug: '', icon: '' },
    { label: 'Europe/Kiev', value: 'Europe/Kiev', slug: '', icon: '' },
    { label: 'Europe/Kirov', value: 'Europe/Kirov', slug: '', icon: '' },
    { label: 'Europe/Lisbon', value: 'Europe/Lisbon', slug: '', icon: '' },
    { label: 'Europe/Ljubljana', value: 'Europe/Ljubljana', slug: '', icon: '' },
    { label: 'Europe/London', value: 'Europe/London', slug: '', icon: '' },
    { label: 'Europe/Luxembourg', value: 'Europe/Luxembourg', slug: '', icon: '' },
    { label: 'Europe/Madrid', value: 'Europe/Madrid', slug: '', icon: '' },
    { label: 'Europe/Malta', value: 'Europe/Malta', slug: '', icon: '' },
    { label: 'Europe/Mariehamn', value: 'Europe/Mariehamn', slug: '', icon: '' },
    { label: 'Europe/Minsk', value: 'Europe/Minsk', slug: '', icon: '' },
    { label: 'Europe/Monaco', value: 'Europe/Monaco', slug: '', icon: '' },
    { label: 'Europe/Moscow', value: 'Europe/Moscow', slug: '', icon: '' },
    { label: 'Europe/Nicosia', value: 'Europe/Nicosia', slug: '', icon: '' },
    { label: 'Europe/Oslo', value: 'Europe/Oslo', slug: '', icon: '' },
    { label: 'Europe/Paris', value: 'Europe/Paris', slug: '', icon: '' },
    { label: 'Europe/Podgorica', value: 'Europe/Podgorica', slug: '', icon: '' },
    { label: 'Europe/Prague', value: 'Europe/Prague', slug: '', icon: '' },
    { label: 'Europe/Riga', value: 'Europe/Riga', slug: '', icon: '' },
    { label: 'Europe/Rome', value: 'Europe/Rome', slug: '', icon: '' },
    { label: 'Europe/Samara', value: 'Europe/Samara', slug: '', icon: '' },
    { label: 'Europe/San_Marino', value: 'Europe/San_Marino', slug: '', icon: '' },
    { label: 'Europe/Sarajevo', value: 'Europe/Sarajevo', slug: '', icon: '' },
    { label: 'Europe/Saratov', value: 'Europe/Saratov', slug: '', icon: '' },
    { label: 'Europe/Simferopol', value: 'Europe/Simferopol', slug: '', icon: '' },
    { label: 'Europe/Skopje', value: 'Europe/Skopje', slug: '', icon: '' },
    { label: 'Europe/Sofia', value: 'Europe/Sofia', slug: '', icon: '' },
    { label: 'Europe/Stockholm', value: 'Europe/Stockholm', slug: '', icon: '' },
    { label: 'Europe/Tallinn', value: 'Europe/Tallinn', slug: '', icon: '' },
    { label: 'Europe/Tirane', value: 'Europe/Tirane', slug: '', icon: '' },
    { label: 'Europe/Tiraspol', value: 'Europe/Tiraspol', slug: '', icon: '' },
    { label: 'Europe/Ulyanovsk', value: 'Europe/Ulyanovsk', slug: '', icon: '' },
    { label: 'Europe/Uzhgorod', value: 'Europe/Uzhgorod', slug: '', icon: '' },
    { label: 'Europe/Vaduz', value: 'Europe/Vaduz', slug: '', icon: '' },
    { label: 'Europe/Vatican', value: 'Europe/Vatican', slug: '', icon: '' },
    { label: 'Europe/Vienna', value: 'Europe/Vienna', slug: '', icon: '' },
    { label: 'Europe/Vilnius', value: 'Europe/Vilnius', slug: '', icon: '' },
    { label: 'Europe/Volgograd', value: 'Europe/Volgograd', slug: '', icon: '' },
    { label: 'Europe/Warsaw', value: 'Europe/Warsaw', slug: '', icon: '' },
    { label: 'Europe/Zagreb', value: 'Europe/Zagreb', slug: '', icon: '' },
    { label: 'Europe/Zaporozhye', value: 'Europe/Zaporozhye', slug: '', icon: '' },
    { label: 'Europe/Zurich', value: 'Europe/Zurich', slug: '', icon: '' },
    { label: 'GB', value: 'GB', slug: '', icon: '' },
    { label: 'GB-Eire', value: 'GB-Eire', slug: '', icon: '' },
    { label: 'GMT', value: 'GMT', slug: '', icon: '' },
    { label: 'GMT+0', value: 'GMT+0', slug: '', icon: '' },
    { label: 'GMT-0', value: 'GMT-0', slug: '', icon: '' },
    { label: 'GMT0', value: 'GMT0', slug: '', icon: '' },
    { label: 'Greenwich', value: 'Greenwich', slug: '', icon: '' },
    { label: 'HST', value: 'HST', slug: '', icon: '' },
    { label: 'Hongkong', value: 'Hongkong', slug: '', icon: '' },
    { label: 'Iceland', value: 'Iceland', slug: '', icon: '' },
    { label: 'Indian/Antananarivo', value: 'Indian/Antananarivo', slug: '', icon: '' },
    { label: 'Indian/Chagos', value: 'Indian/Chagos', slug: '', icon: '' },
    { label: 'Indian/Christmas', value: 'Indian/Christmas', slug: '', icon: '' },
    { label: 'Indian/Cocos', value: 'Indian/Cocos', slug: '', icon: '' },
    { label: 'Indian/Comoro', value: 'Indian/Comoro', slug: '', icon: '' },
    { label: 'Indian/Kerguelen', value: 'Indian/Kerguelen', slug: '', icon: '' },
    { label: 'Indian/Mahe', value: 'Indian/Mahe', slug: '', icon: '' },
    { label: 'Indian/Maldives', value: 'Indian/Maldives', slug: '', icon: '' },
    { label: 'Indian/Mauritius', value: 'Indian/Mauritius', slug: '', icon: '' },
    { label: 'Indian/Mayotte', value: 'Indian/Mayotte', slug: '', icon: '' },
    { label: 'Indian/Reunion', value: 'Indian/Reunion', slug: '', icon: '' },
    { label: 'Iran', value: 'Iran', slug: '', icon: '' },
    { label: 'Israel', value: 'Israel', slug: '', icon: '' },
    { label: 'Jamaica', value: 'Jamaica', slug: '', icon: '' },
    { label: 'Japan', value: 'Japan', slug: '', icon: '' },
    { label: 'Kwajalein', value: 'Kwajalein', slug: '', icon: '' },
    { label: 'Libya', value: 'Libya', slug: '', icon: '' },
    { label: 'MET', value: 'MET', slug: '', icon: '' },
    { label: 'MST', value: 'MST', slug: '', icon: '' },
    { label: 'MST7MDT', value: 'MST7MDT', slug: '', icon: '' },
    { label: 'Mexico/BajaNorte', value: 'Mexico/BajaNorte', slug: '', icon: '' },
    { label: 'Mexico/BajaSur', value: 'Mexico/BajaSur', slug: '', icon: '' },
    { label: 'Mexico/General', value: 'Mexico/General', slug: '', icon: '' },
    { label: 'NZ', value: 'NZ', slug: '', icon: '' },
    { label: 'NZ-CHAT', value: 'NZ-CHAT', slug: '', icon: '' },
    { label: 'Navajo', value: 'Navajo', slug: '', icon: '' },
    { label: 'PRC', value: 'PRC', slug: '', icon: '' },
    { label: 'PST8PDT', value: 'PST8PDT', slug: '', icon: '' },
    { label: 'Pacific/Apia', value: 'Pacific/Apia', slug: '', icon: '' },
    { label: 'Pacific/Auckland', value: 'Pacific/Auckland', slug: '', icon: '' },
    { label: 'Pacific/Bougainville', value: 'Pacific/Bougainville', slug: '', icon: '' },
    { label: 'Pacific/Chatham', value: 'Pacific/Chatham', slug: '', icon: '' },
    { label: 'Pacific/Chuuk', value: 'Pacific/Chuuk', slug: '', icon: '' },
    { label: 'Pacific/Easter', value: 'Pacific/Easter', slug: '', icon: '' },
    { label: 'Pacific/Efate', value: 'Pacific/Efate', slug: '', icon: '' },
    { label: 'Pacific/Enderbury', value: 'Pacific/Enderbury', slug: '', icon: '' },
    { label: 'Pacific/Fakaofo', value: 'Pacific/Fakaofo', slug: '', icon: '' },
    { label: 'Pacific/Fiji', value: 'Pacific/Fiji', slug: '', icon: '' },
    { label: 'Pacific/Funafuti', value: 'Pacific/Funafuti', slug: '', icon: '' },
    { label: 'Pacific/Galapagos', value: 'Pacific/Galapagos', slug: '', icon: '' },
    { label: 'Pacific/Gambier', value: 'Pacific/Gambier', slug: '', icon: '' },
    { label: 'Pacific/Guadalcanal', value: 'Pacific/Guadalcanal', slug: '', icon: '' },
    { label: 'Pacific/Guam', value: 'Pacific/Guam', slug: '', icon: '' },
    { label: 'Pacific/Honolulu', value: 'Pacific/Honolulu', slug: '', icon: '' },
    { label: 'Pacific/Johnston', value: 'Pacific/Johnston', slug: '', icon: '' },
    { label: 'Pacific/Kanton', value: 'Pacific/Kanton', slug: '', icon: '' },
    { label: 'Pacific/Kiritimati', value: 'Pacific/Kiritimati', slug: '', icon: '' },
    { label: 'Pacific/Kosrae', value: 'Pacific/Kosrae', slug: '', icon: '' },
    { label: 'Pacific/Kwajalein', value: 'Pacific/Kwajalein', slug: '', icon: '' },
    { label: 'Pacific/Majuro', value: 'Pacific/Majuro', slug: '', icon: '' },
    { label: 'Pacific/Marquesas', value: 'Pacific/Marquesas', slug: '', icon: '' },
    { label: 'Pacific/Midway', value: 'Pacific/Midway', slug: '', icon: '' },
    { label: 'Pacific/Nauru', value: 'Pacific/Nauru', slug: '', icon: '' },
    { label: 'Pacific/Niue', value: 'Pacific/Niue', slug: '', icon: '' },
    { label: 'Pacific/Norfolk', value: 'Pacific/Norfolk', slug: '', icon: '' },
    { label: 'Pacific/Noumea', value: 'Pacific/Noumea', slug: '', icon: '' },
    { label: 'Pacific/Pago_Pago', value: 'Pacific/Pago_Pago', slug: '', icon: '' },
    { label: 'Pacific/Palau', value: 'Pacific/Palau', slug: '', icon: '' },
    { label: 'Pacific/Pitcairn', value: 'Pacific/Pitcairn', slug: '', icon: '' },
    { label: 'Pacific/Pohnpei', value: 'Pacific/Pohnpei', slug: '', icon: '' },
    { label: 'Pacific/Ponape', value: 'Pacific/Ponape', slug: '', icon: '' },
    { label: 'Pacific/Port_Moresby', value: 'Pacific/Port_Moresby', slug: '', icon: '' },
    { label: 'Pacific/Rarotonga', value: 'Pacific/Rarotonga', slug: '', icon: '' },
    { label: 'Pacific/Saipan', value: 'Pacific/Saipan', slug: '', icon: '' },
    { label: 'Pacific/Samoa', value: 'Pacific/Samoa', slug: '', icon: '' },
    { label: 'Pacific/Tahiti', value: 'Pacific/Tahiti', slug: '', icon: '' },
    { label: 'Pacific/Tarawa', value: 'Pacific/Tarawa', slug: '', icon: '' },
    { label: 'Pacific/Tongatapu', value: 'Pacific/Tongatapu', slug: '', icon: '' },
    { label: 'Pacific/Truk', value: 'Pacific/Truk', slug: '', icon: '' },
    { label: 'Pacific/Wake', value: 'Pacific/Wake', slug: '', icon: '' },
    { label: 'Pacific/Wallis', value: 'Pacific/Wallis', slug: '', icon: '' },
    { label: 'Pacific/Yap', value: 'Pacific/Yap', slug: '', icon: '' },
    { label: 'Poland', value: 'Poland', slug: '', icon: '' },
    { label: 'Portugal', value: 'Portugal', slug: '', icon: '' },
    { label: 'ROC', value: 'ROC', slug: '', icon: '' },
    { label: 'ROK', value: 'ROK', slug: '', icon: '' },
    { label: 'Singapore', value: 'Singapore', slug: '', icon: '' },
    { label: 'Turkey', value: 'Turkey', slug: '', icon: '' },
    { label: 'UCT', value: 'UCT', slug: '', icon: '' },
    { label: 'US/Alaska', value: 'US/Alaska', slug: '', icon: '' },
    { label: 'US/Aleutian', value: 'US/Aleutian', slug: '', icon: '' },
    { label: 'US/Arizona', value: 'US/Arizona', slug: '', icon: '' },
    { label: 'US/Central', value: 'US/Central', slug: '', icon: '' },
    { label: 'US/East-Indiana', value: 'US/East-Indiana', slug: '', icon: '' },
    { label: 'US/Eastern', value: 'US/Eastern', slug: '', icon: '' },
    { label: 'US/Hawaii', value: 'US/Hawaii', slug: '', icon: '' },
    { label: 'US/Indiana-Starke', value: 'US/Indiana-Starke', slug: '', icon: '' },
    { label: 'US/Michigan', value: 'US/Michigan', slug: '', icon: '' },
    { label: 'US/Mountain', value: 'US/Mountain', slug: '', icon: '' },
    { label: 'US/Pacific', value: 'US/Pacific', slug: '', icon: '' },
    { label: 'US/Samoa', value: 'US/Samoa', slug: '', icon: '' },
    { label: 'UTC', value: 'UTC', slug: '', icon: '' },
    { label: 'Universal', value: 'Universal', slug: '', icon: '' },
    { label: 'W-SU', value: 'W-SU', slug: '', icon: '' },
    { label: 'WET', value: 'WET', slug: '', icon: '' },
    { label: 'Zulu', value: 'Zulu', slug: '', icon: '' },
];

// All simple ISO 3166 country data
// including: 2-character, 3-character, full country name and numeric code.
// Sorted alphabetical by country name (special characters on bottom)
export const countryListAllIsoData = [
	{"code": "AF", "code3": "AFG", "name": "Afghanistan", "number": "004"},
	{"code": "AL", "code3": "ALB", "name": "Albania", "number": "008"},
	{"code": "DZ", "code3": "DZA", "name": "Algeria", "number": "012"},
	{"code": "AS", "code3": "ASM", "name": "American Samoa", "number": "016"},
	{"code": "AD", "code3": "AND", "name": "Andorra", "number": "020"},
	{"code": "AO", "code3": "AGO", "name": "Angola", "number": "024"},
	{"code": "AI", "code3": "AIA", "name": "Anguilla", "number": "660"},
	{"code": "AQ", "code3": "ATA", "name": "Antarctica", "number": "010"},
	{"code": "AG", "code3": "ATG", "name": "Antigua and Barbuda", "number": "028"},
	{"code": "AR", "code3": "ARG", "name": "Argentina", "number": "032"},
	{"code": "AM", "code3": "ARM", "name": "Armenia", "number": "051"},
	{"code": "AW", "code3": "ABW", "name": "Aruba", "number": "533"},
	{"code": "AU", "code3": "AUS", "name": "Australia", "number": "036"},
	{"code": "AT", "code3": "AUT", "name": "Austria", "number": "040"},
	{"code": "AZ", "code3": "AZE", "name": "Azerbaijan", "number": "031"},
	{"code": "BS", "code3": "BHS", "name": "Bahamas", "number": "044"},
	{"code": "BH", "code3": "BHR", "name": "Bahrain", "number": "048"},
	{"code": "BD", "code3": "BGD", "name": "Bangladesh", "number": "050"},
	{"code": "BB", "code3": "BRB", "name": "Barbados", "number": "052"},
	{"code": "BY", "code3": "BLR", "name": "Belarus", "number": "112"},
	{"code": "BE", "code3": "BEL", "name": "Belgium", "number": "056"},
	{"code": "BZ", "code3": "BLZ", "name": "Belize", "number": "084"},
	{"code": "BJ", "code3": "BEN", "name": "Benin", "number": "204"},
	{"code": "BM", "code3": "BMU", "name": "Bermuda", "number": "060"},
	{"code": "BT", "code3": "BTN", "name": "Bhutan", "number": "064"},
	{"code": "BO", "code3": "BOL", "name": "Bolivia (Plurinational State of)", "number": "068"},
	{"code": "BQ", "code3": "BES", "name": "Bonaire, Sint Eustatius and Saba", "number": "535"},
	{"code": "BA", "code3": "BIH", "name": "Bosnia and Herzegovina", "number": "070"},
	{"code": "BW", "code3": "BWA", "name": "Botswana", "number": "072"},
	{"code": "BV", "code3": "BVT", "name": "Bouvet Island", "number": "074"},
	{"code": "BR", "code3": "BRA", "name": "Brazil", "number": "076"},
	{"code": "IO", "code3": "IOT", "name": "British Indian Ocean Territory", "number": "086"},
	{"code": "BN", "code3": "BRN", "name": "Brunei Darussalam", "number": "096"},
	{"code": "BG", "code3": "BGR", "name": "Bulgaria", "number": "100"},
	{"code": "BF", "code3": "BFA", "name": "Burkina Faso", "number": "854"},
	{"code": "BI", "code3": "BDI", "name": "Burundi", "number": "108"},
	{"code": "CV", "code3": "CPV", "name": "Cabo Verde", "number": "132"},
	{"code": "KH", "code3": "KHM", "name": "Cambodia", "number": "116"},
	{"code": "CM", "code3": "CMR", "name": "Cameroon", "number": "120"},
	{"code": "CA", "code3": "CAN", "name": "Canada", "number": "124"},
	{"code": "KY", "code3": "CYM", "name": "Cayman Islands", "number": "136"},
	{"code": "CF", "code3": "CAF", "name": "Central African Republic", "number": "140"},
	{"code": "TD", "code3": "TCD", "name": "Chad", "number": "148"},
	{"code": "CL", "code3": "CHL", "name": "Chile", "number": "152"},
	{"code": "CN", "code3": "CHN", "name": "China", "number": "156"},
	{"code": "CX", "code3": "CXR", "name": "Christmas Island", "number": "162"},
	{"code": "CC", "code3": "CCK", "name": "Cocos (Keeling) Islands", "number": "166"},
	{"code": "CO", "code3": "COL", "name": "Colombia", "number": "170"},
	{"code": "KM", "code3": "COM", "name": "Comoros", "number": "174"},
	{"code": "CD", "code3": "COD", "name": "Congo (the Democratic Republic of the)", "number": "180"},
	{"code": "CG", "code3": "COG", "name": "Congo", "number": "178"},
	{"code": "CK", "code3": "COK", "name": "Cook Islands", "number": "184"},
	{"code": "CR", "code3": "CRI", "name": "Costa Rica", "number": "188"},
	{"code": "HR", "code3": "HRV", "name": "Croatia", "number": "191"},
	{"code": "CU", "code3": "CUB", "name": "Cuba", "number": "192"},
	{"code": "CW", "code3": "CUW", "name": "Curaçao", "number": "531"},
	{"code": "CY", "code3": "CYP", "name": "Cyprus", "number": "196"},
	{"code": "CZ", "code3": "CZE", "name": "Czechia", "number": "203"},
	{"code": "CI", "code3": "CIV", "name": "Côte d'Ivoire", "number": "384"},
	{"code": "DK", "code3": "DNK", "name": "Denmark", "number": "208"},
	{"code": "DJ", "code3": "DJI", "name": "Djibouti", "number": "262"},
	{"code": "DM", "code3": "DMA", "name": "Dominica", "number": "212"},
	{"code": "DO", "code3": "DOM", "name": "Dominican Republic", "number": "214"},
	{"code": "EC", "code3": "ECU", "name": "Ecuador", "number": "218"},
	{"code": "EG", "code3": "EGY", "name": "Egypt", "number": "818"},
	{"code": "SV", "code3": "SLV", "name": "El Salvador", "number": "222"},
	{"code": "GQ", "code3": "GNQ", "name": "Equatorial Guinea", "number": "226"},
	{"code": "ER", "code3": "ERI", "name": "Eritrea", "number": "232"},
	{"code": "EE", "code3": "EST", "name": "Estonia", "number": "233"},
	{"code": "SZ", "code3": "SWZ", "name": "Eswatini", "number": "748"},
	{"code": "ET", "code3": "ETH", "name": "Ethiopia", "number": "231"},
	{"code": "FK", "code3": "FLK", "name": "Falkland Islands [Malvinas]", "number": "238"},
	{"code": "FO", "code3": "FRO", "name": "Faroe Islands", "number": "234"},
	{"code": "FJ", "code3": "FJI", "name": "Fiji", "number": "242"},
	{"code": "FI", "code3": "FIN", "name": "Finland", "number": "246"},
	{"code": "FR", "code3": "FRA", "name": "France", "number": "250"},
	{"code": "GF", "code3": "GUF", "name": "French Guiana", "number": "254"},
	{"code": "PF", "code3": "PYF", "name": "French Polynesia", "number": "258"},
	{"code": "TF", "code3": "ATF", "name": "French Southern Territories", "number": "260"},
	{"code": "GA", "code3": "GAB", "name": "Gabon", "number": "266"},
	{"code": "GM", "code3": "GMB", "name": "Gambia", "number": "270"},
	{"code": "GE", "code3": "GEO", "name": "Georgia", "number": "268"},
	{"code": "DE", "code3": "DEU", "name": "Germany", "number": "276"},
	{"code": "GH", "code3": "GHA", "name": "Ghana", "number": "288"},
	{"code": "GI", "code3": "GIB", "name": "Gibraltar", "number": "292"},
	{"code": "GR", "code3": "GRC", "name": "Greece", "number": "300"},
	{"code": "GL", "code3": "GRL", "name": "Greenland", "number": "304"},
	{"code": "GD", "code3": "GRD", "name": "Grenada", "number": "308"},
	{"code": "GP", "code3": "GLP", "name": "Guadeloupe", "number": "312"},
	{"code": "GU", "code3": "GUM", "name": "Guam", "number": "316"},
	{"code": "GT", "code3": "GTM", "name": "Guatemala", "number": "320"},
	{"code": "GG", "code3": "GGY", "name": "Guernsey", "number": "831"},
	{"code": "GN", "code3": "GIN", "name": "Guinea", "number": "324"},
	{"code": "GW", "code3": "GNB", "name": "Guinea-Bissau", "number": "624"},
	{"code": "GY", "code3": "GUY", "name": "Guyana", "number": "328"},
	{"code": "HT", "code3": "HTI", "name": "Haiti", "number": "332"},
	{"code": "HM", "code3": "HMD", "name": "Heard Island and McDonald Islands", "number": "334"},
	{"code": "VA", "code3": "VAT", "name": "Holy See", "number": "336"},
	{"code": "HN", "code3": "HND", "name": "Honduras", "number": "340"},
	{"code": "HK", "code3": "HKG", "name": "Hong Kong", "number": "344"},
	{"code": "HU", "code3": "HUN", "name": "Hungary", "number": "348"},
	{"code": "IS", "code3": "ISL", "name": "Iceland", "number": "352"},
	{"code": "IN", "code3": "IND", "name": "India", "number": "356"},
	{"code": "ID", "code3": "IDN", "name": "Indonesia", "number": "360"},
	{"code": "IR", "code3": "IRN", "name": "Iran (Islamic Republic of)", "number": "364"},
	{"code": "IQ", "code3": "IRQ", "name": "Iraq", "number": "368"},
	{"code": "IE", "code3": "IRL", "name": "Ireland", "number": "372"},
	{"code": "IM", "code3": "IMN", "name": "Isle of Man", "number": "833"},
	{"code": "IL", "code3": "ISR", "name": "Israel", "number": "376"},
	{"code": "IT", "code3": "ITA", "name": "Italy", "number": "380"},
	{"code": "JM", "code3": "JAM", "name": "Jamaica", "number": "388"},
	{"code": "JP", "code3": "JPN", "name": "Japan", "number": "392"},
	{"code": "JE", "code3": "JEY", "name": "Jersey", "number": "832"},
	{"code": "JO", "code3": "JOR", "name": "Jordan", "number": "400"},
	{"code": "KZ", "code3": "KAZ", "name": "Kazakhstan", "number": "398"},
	{"code": "KE", "code3": "KEN", "name": "Kenya", "number": "404"},
	{"code": "KI", "code3": "KIR", "name": "Kiribati", "number": "296"},
	{"code": "KP", "code3": "PRK", "name": "Korea (the Democratic People's Republic of)", "number": "408"},
	{"code": "KR", "code3": "KOR", "name": "Korea (the Republic of)", "number": "410"},
	{"code": "KW", "code3": "KWT", "name": "Kuwait", "number": "414"},
	{"code": "KG", "code3": "KGZ", "name": "Kyrgyzstan", "number": "417"},
	{"code": "LA", "code3": "LAO", "name": "Lao People's Democratic Republic", "number": "418"},
	{"code": "LV", "code3": "LVA", "name": "Latvia", "number": "428"},
	{"code": "LB", "code3": "LBN", "name": "Lebanon", "number": "422"},
	{"code": "LS", "code3": "LSO", "name": "Lesotho", "number": "426"},
	{"code": "LR", "code3": "LBR", "name": "Liberia", "number": "430"},
	{"code": "LY", "code3": "LBY", "name": "Libya", "number": "434"},
	{"code": "LI", "code3": "LIE", "name": "Liechtenstein", "number": "438"},
	{"code": "LT", "code3": "LTU", "name": "Lithuania", "number": "440"},
	{"code": "LU", "code3": "LUX", "name": "Luxembourg", "number": "442"},
	{"code": "MO", "code3": "MAC", "name": "Macao", "number": "446"},
	{"code": "MG", "code3": "MDG", "name": "Madagascar", "number": "450"},
	{"code": "MW", "code3": "MWI", "name": "Malawi", "number": "454"},
	{"code": "MY", "code3": "MYS", "name": "Malaysia", "number": "458"},
	{"code": "MV", "code3": "MDV", "name": "Maldives", "number": "462"},
	{"code": "ML", "code3": "MLI", "name": "Mali", "number": "466"},
	{"code": "MT", "code3": "MLT", "name": "Malta", "number": "470"},
	{"code": "MH", "code3": "MHL", "name": "Marshall Islands", "number": "584"},
	{"code": "MQ", "code3": "MTQ", "name": "Martinique", "number": "474"},
	{"code": "MR", "code3": "MRT", "name": "Mauritania", "number": "478"},
	{"code": "MU", "code3": "MUS", "name": "Mauritius", "number": "480"},
	{"code": "YT", "code3": "MYT", "name": "Mayotte", "number": "175"},
	{"code": "MX", "code3": "MEX", "name": "Mexico", "number": "484"},
	{"code": "FM", "code3": "FSM", "name": "Micronesia (Federated States of)", "number": "583"},
	{"code": "MD", "code3": "MDA", "name": "Moldova (the Republic of)", "number": "498"},
	{"code": "MC", "code3": "MCO", "name": "Monaco", "number": "492"},
	{"code": "MN", "code3": "MNG", "name": "Mongolia", "number": "496"},
	{"code": "ME", "code3": "MNE", "name": "Montenegro", "number": "499"},
	{"code": "MS", "code3": "MSR", "name": "Montserrat", "number": "500"},
	{"code": "MA", "code3": "MAR", "name": "Morocco", "number": "504"},
	{"code": "MZ", "code3": "MOZ", "name": "Mozambique", "number": "508"},
	{"code": "MM", "code3": "MMR", "name": "Myanmar", "number": "104"},
	{"code": "NA", "code3": "NAM", "name": "Namibia", "number": "516"},
	{"code": "NR", "code3": "NRU", "name": "Nauru", "number": "520"},
	{"code": "NP", "code3": "NPL", "name": "Nepal", "number": "524"},
	{"code": "NL", "code3": "NLD", "name": "Netherlands", "number": "528"},
	{"code": "NC", "code3": "NCL", "name": "New Caledonia", "number": "540"},
	{"code": "NZ", "code3": "NZL", "name": "New Zealand", "number": "554"},
	{"code": "NI", "code3": "NIC", "name": "Nicaragua", "number": "558"},
	{"code": "NE", "code3": "NER", "name": "Niger", "number": "562"},
	{"code": "NG", "code3": "NGA", "name": "Nigeria", "number": "566"},
	{"code": "NU", "code3": "NIU", "name": "Niue", "number": "570"},
	{"code": "NF", "code3": "NFK", "name": "Norfolk Island", "number": "574"},
	{"code": "MP", "code3": "MNP", "name": "Northern Mariana Islands", "number": "580"},
	{"code": "NO", "code3": "NOR", "name": "Norway", "number": "578"},
	{"code": "OM", "code3": "OMN", "name": "Oman", "number": "512"},
	{"code": "PK", "code3": "PAK", "name": "Pakistan", "number": "586"},
	{"code": "PW", "code3": "PLW", "name": "Palau", "number": "585"},
	{"code": "PS", "code3": "PSE", "name": "Palestine, State of", "number": "275"},
	{"code": "PA", "code3": "PAN", "name": "Panama", "number": "591"},
	{"code": "PG", "code3": "PNG", "name": "Papua New Guinea", "number": "598"},
	{"code": "PY", "code3": "PRY", "name": "Paraguay", "number": "600"},
	{"code": "PE", "code3": "PER", "name": "Peru", "number": "604"},
	{"code": "PH", "code3": "PHL", "name": "Philippines", "number": "608"},
	{"code": "PN", "code3": "PCN", "name": "Pitcairn", "number": "612"},
	{"code": "PL", "code3": "POL", "name": "Poland", "number": "616"},
	{"code": "PT", "code3": "PRT", "name": "Portugal", "number": "620"},
	{"code": "PR", "code3": "PRI", "name": "Puerto Rico", "number": "630"},
	{"code": "QA", "code3": "QAT", "name": "Qatar", "number": "634"},
	{"code": "MK", "code3": "MKD", "name": "Republic of North Macedonia", "number": "807"},
	{"code": "RO", "code3": "ROU", "name": "Romania", "number": "642"},
	{"code": "RU", "code3": "RUS", "name": "Russian Federation", "number": "643"},
	{"code": "RW", "code3": "RWA", "name": "Rwanda", "number": "646"},
	{"code": "RE", "code3": "REU", "name": "Réunion", "number": "638"},
	{"code": "BL", "code3": "BLM", "name": "Saint Barthélemy", "number": "652"},
	{"code": "SH", "code3": "SHN", "name": "Saint Helena, Ascension and Tristan da Cunha", "number": "654"},
	{"code": "KN", "code3": "KNA", "name": "Saint Kitts and Nevis", "number": "659"},
	{"code": "LC", "code3": "LCA", "name": "Saint Lucia", "number": "662"},
	{"code": "MF", "code3": "MAF", "name": "Saint Martin (French part)", "number": "663"},
	{"code": "PM", "code3": "SPM", "name": "Saint Pierre and Miquelon", "number": "666"},
	{"code": "VC", "code3": "VCT", "name": "Saint Vincent and the Grenadines", "number": "670"},
	{"code": "WS", "code3": "WSM", "name": "Samoa", "number": "882"},
	{"code": "SM", "code3": "SMR", "name": "San Marino", "number": "674"},
	{"code": "ST", "code3": "STP", "name": "Sao Tome and Principe", "number": "678"},
	{"code": "SA", "code3": "SAU", "name": "Saudi Arabia", "number": "682"},
	{"code": "SN", "code3": "SEN", "name": "Senegal", "number": "686"},
	{"code": "RS", "code3": "SRB", "name": "Serbia", "number": "688"},
	{"code": "SC", "code3": "SYC", "name": "Seychelles", "number": "690"},
	{"code": "SL", "code3": "SLE", "name": "Sierra Leone", "number": "694"},
	{"code": "SG", "code3": "SGP", "name": "Singapore", "number": "702"},
	{"code": "SX", "code3": "SXM", "name": "Sint Maarten (Dutch part)", "number": "534"},
	{"code": "SK", "code3": "SVK", "name": "Slovakia", "number": "703"},
	{"code": "SI", "code3": "SVN", "name": "Slovenia", "number": "705"},
	{"code": "SB", "code3": "SLB", "name": "Solomon Islands", "number": "090"},
	{"code": "SO", "code3": "SOM", "name": "Somalia", "number": "706"},
	{"code": "ZA", "code3": "ZAF", "name": "South Africa", "number": "710"},
	{"code": "GS", "code3": "SGS", "name": "South Georgia and the South Sandwich Islands", "number": "239"},
	{"code": "SS", "code3": "SSD", "name": "South Sudan", "number": "728"},
	{"code": "ES", "code3": "ESP", "name": "Spain", "number": "724"},
	{"code": "LK", "code3": "LKA", "name": "Sri Lanka", "number": "144"},
	{"code": "SD", "code3": "SDN", "name": "Sudan", "number": "729"},
	{"code": "SR", "code3": "SUR", "name": "Suriname", "number": "740"},
	{"code": "SJ", "code3": "SJM", "name": "Svalbard and Jan Mayen", "number": "744"},
	{"code": "SE", "code3": "SWE", "name": "Sweden", "number": "752"},
	{"code": "CH", "code3": "CHE", "name": "Switzerland", "number": "756"},
	{"code": "SY", "code3": "SYR", "name": "Syrian Arab Republic", "number": "760"},
	{"code": "TW", "code3": "TWN", "name": "Taiwan", "number": "158"},
	{"code": "TJ", "code3": "TJK", "name": "Tajikistan", "number": "762"},
	{"code": "TZ", "code3": "TZA", "name": "Tanzania, United Republic of", "number": "834"},
	{"code": "TH", "code3": "THA", "name": "Thailand", "number": "764"},
	{"code": "TL", "code3": "TLS", "name": "Timor-Leste", "number": "626"},
	{"code": "TG", "code3": "TGO", "name": "Togo", "number": "768"},
	{"code": "TK", "code3": "TKL", "name": "Tokelau", "number": "772"},
	{"code": "TO", "code3": "TON", "name": "Tonga", "number": "776"},
	{"code": "TT", "code3": "TTO", "name": "Trinidad and Tobago", "number": "780"},
	{"code": "TN", "code3": "TUN", "name": "Tunisia", "number": "788"},
	{"code": "TR", "code3": "TUR", "name": "Turkey", "number": "792"},
	{"code": "TM", "code3": "TKM", "name": "Turkmenistan", "number": "795"},
	{"code": "TC", "code3": "TCA", "name": "Turks and Caicos Islands", "number": "796"},
	{"code": "TV", "code3": "TUV", "name": "Tuvalu", "number": "798"},
	{"code": "UG", "code3": "UGA", "name": "Uganda", "number": "800"},
	{"code": "UA", "code3": "UKR", "name": "Ukraine", "number": "804"},
	{"code": "AE", "code3": "ARE", "name": "United Arab Emirates", "number": "784"},
	{"code": "GB", "code3": "GBR", "name": "United Kingdom of Great Britain and Northern Ireland", "number": "826"},
	{"code": "UM", "code3": "UMI", "name": "United States Minor Outlying Islands", "number": "581"},
	{"code": "US", "code3": "USA", "name": "United States of America", "number": "840"},
	{"code": "UY", "code3": "URY", "name": "Uruguay", "number": "858"},
	{"code": "UZ", "code3": "UZB", "name": "Uzbekistan", "number": "860"},
	{"code": "VU", "code3": "VUT", "name": "Vanuatu", "number": "548"},
	{"code": "VE", "code3": "VEN", "name": "Venezuela (Bolivarian Republic of)", "number": "862"},
	{"code": "VN", "code3": "VNM", "name": "Viet Nam", "number": "704"},
	{"code": "VG", "code3": "VGB", "name": "Virgin Islands (British)", "number": "092"},
	{"code": "VI", "code3": "VIR", "name": "Virgin Islands (U.S.)", "number": "850"},
	{"code": "WF", "code3": "WLF", "name": "Wallis and Futuna", "number": "876"},
	{"code": "EH", "code3": "ESH", "name": "Western Sahara", "number": "732"},
	{"code": "YE", "code3": "YEM", "name": "Yemen", "number": "887"},
	{"code": "ZM", "code3": "ZMB", "name": "Zambia", "number": "894"},
	{"code": "ZW", "code3": "ZWE", "name": "Zimbabwe", "number": "716"},
	{"code": "AX", "code3": "ALA", "name": "Åland Islands", "number": "248"}
];